=== RupinderKaurSSB/linked-data-store-core/src/main/resources/spec/v1/schemas/AgentInRole.json
{
  "$ref" : "#/definitions/AgentInRole",
  "definitions" : {
    "MultilingualText" : {
      "type" : "object",
      "properties" : {
        "languageCode" : {
          "type" : "string"
        },
        "languageText" : {
          "type" : "string"
        }
      },
      "required" : [ "languageCode", "languageText" ]
    },
    "AgentInRole" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "agentInRoleDescription" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/MultilingualText"
          }
        },
        "role" : {
          "type" : "string"
        },
        "_link_property_role" : {
          "type" : "object",
          "properties" : {
            "Role": {
              "type" : "null"
            }
          }
        },
        "agents" : {
          "type" : "array",
          "items" : {
            "type" : "string"
          }
        },
        "_link_property_agents" : {
          "type" : "object",
          "properties" : {
            "Agent": {
              "type" : "null"
            }
          }
        }
      },
      "required" : [ "id", "role", "agents" ]
    }
  },
  "$schema" : "http://json-schema.org/draft-04/schema#"
}

=== RupinderKaurSSB/linked-data-store-core/src/test/resources/spec/v1/examples/AgentInRoleExample.json
{
  "id": "d1f8e3b7-0eb3-4a6d-91bb-a7451649f2f6",
  "agentInRoleDescription": [
    {
      "languageCode": "nb",
      "languageText": "Disse objektene eies av A300 og A700 i fellesskap"
    }
  ],
  "role": "4eea64e6-5c87-462d-9fc5-c3fdd3a310fa",
  "agents": [
    "1d6ca477-4d0c-47b1-967d-1bead9c1b56b",
    "91712998-84a5-4f6c-8053-4dfaafa7c0e3"
  ]
}
